//SERVER SIDE ERROR HANDLING
..using try catch(handle error)

&
app.use((err, req, res, next) => {
    res.send("something went wrong!);
});